In [31]:
import numpy as np

Definição de dois vetores colunas

In [36]:
x = np.asmatrix([[1],[2]])
y = np.asmatrix ([[1],[2]])


print (x)
print (y)

[[1]
 [2]]
[[1]
 [2]]


Soma de dois vetores colunas

In [37]:
print (x+y)

[[2]
 [4]]


Produto interno entre dois vetores

In [42]:
z = np.asmatrix([[1],[2]])
w = np.asmatrix ([[1,2]])

print (z*w)

[[1 2]
 [2 4]]


Comprimento/Norma de um vetor

Matriz 2x2

In [ ]:
A = np.asmatrix([[1,2],[3,4]])
B = np.asmatrix([[1],[2]])
print(A)
print(B)

print (A*B)

[[1 2]
 [3 4]]
[[1]
 [2]]
[[ 5]
 [11]]


In [54]:
A = np.asmatrix([[1,2],[3,4]])
B = np.asmatrix([[1,2],[3,4]])
print(A)
print(B)

print (A*B)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[ 7 10]
 [15 22]]


Matriz Quadrada

In [56]:
determinante = np.linalg.det(A)
print (determinante)

-2.0000000000000004


In [71]:
I = np.asmatrix([[1,0],[0,1]])
inversa = (A.I)
print (inversa)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [67]:
print(A.I*A)

[[1.00000000e+00 0.00000000e+00]
 [1.11022302e-16 1.00000000e+00]]


In [3]:
from osgeo import gdal